version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=slowco
      - POSTGRES_PASSWORD=slowco
      - POSTGRES_DB=slowco
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://slowco:slowco@host.docker.internal:5432/slowco?schema=public
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    networks:
      - app_network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/app/node_modules
      - /app/apps/api/node_modules

networks:
  app_network:
    external: true

volumes:
  postgres:
