name = "snail"
main = "dist/index.mjs"
compatibility_date = "2022-12-24"

kv_namespaces = [
  { binding = "KV", id = "f86c2743d9e74b15a15d87244880a34d" }
]

[build]
command = "pnpm build"
watch_dir = "src"

[miniflare]
watch = true
live_reload = true
kv_persist = true
cache_persist = "./cache"
cache = true
[build.upload]
format = "modules"
